# Generated by Django 5.1.3 on 2024-11-10 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meseros', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='meses',
            new_name='meseros',
        ),
    ]
